/**
 * Site footer
 * 
 * Minimal footer with credits and source attribution.
 * Should feel like a quiet ending, not a call to action.
 */

export function Footer() {
  return (
    <footer className="relative z-10 border-t border-shadow-800/30 mt-auto">
      <div className="container-wide py-8">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-shadow-500">
          {/* Attribution */}
          <p className="font-ui">
            Boards generated by{' '}
            <a 
              href="https://bingobrawlers.com" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-parchment-400 hover:text-gold-400 transition-colors underline underline-offset-2 decoration-shadow-600 hover:decoration-gold-600"
            >
              Bingo Brawlers
            </a>
          </p>

          {/* Decorative divider */}
          <div className="hidden md:block w-px h-4 bg-shadow-700" />

          {/* Tagline */}
          <p className="font-body text-shadow-600">
            Match archive
          </p>
        </div>
      </div>
    </footer>
  )
}
